2025-06-15 09:24:08 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:24:08 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:24:08 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:24:15 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:15 INFO Run function 8 complete. FEHistory len: 550, AOCC: 0.0000
2025-06-15 09:24:15 INFO FeHistory: [177737.97933934 171392.09673438 173575.536656   167278.41556601
 173120.03009333 170893.95514775 173135.48374455 172743.54276344
 161620.23944163 160607.90994915 167011.58539218 166350.19427524
 164919.47271842 164306.98538388 163880.20431603 159381.50612118
 160516.80088873 167557.30507773 173006.45068832 154656.93241048
 157452.96511696 160202.80662244 149876.13973222 147851.74579325
 144409.01374648 145535.49319779 144458.10541378 143513.90494539
 155561.00903204 143437.81177343 141602.69073375 140758.02459633
 144496.94397879 139113.04289732 137874.13715385 135459.68749306
 135086.20599485 136018.58867555 138310.7144618  138002.36912465
 133931.64299656 134672.5500475  135506.94101399 135457.33672965
 137213.7978823  133560.65277141 134915.50413976 137988.58737753
 136786.2787478  136046.95190756 136280.20148418 130186.90430293
 131944.65233849 130829.85055445 132478.51341351 131178.72924529
 126389.34661791 122924.46687958 124445.26518861 122614.01095312
 121027.83328968 121522.73243899 123417.64777779 121906.91004141
 122068.88558468 123129.32751719 120224.50454199 121132.74256113
 121460.77045462 120392.38244888 121217.42737398 120449.58526746
 120205.51484055 120017.79978022 120608.21823798 119320.73338824
 118764.44235351 119716.0116753  118396.22333459 117960.63936987
 116886.10193388 117432.206753   116581.75463629 117432.27781113
 117361.65634892 116186.16558805 115264.93693598 115873.16351554
 115980.0618564  115610.17560516 115100.77949115 115903.71257901
 116378.93107386 114924.11693495 115578.69244826 114070.427629
 113962.2702573  114099.00158037 115139.07183287 113616.04542179
 113724.0062167  113006.38751082 113189.50996394 112194.67823357
 112389.83483854 111713.8667203  111880.69901392 112874.95943049
 111768.30169299 111529.0236573  111375.27437738 110479.87418146
 110594.40440633 110663.04982556 109614.0928231  109378.22816676
 109460.63407539 109527.81568768 109094.82887868 109662.48846473
 109202.82839146 108772.74321732 109670.96937187 109302.30484044
 108249.90258378 108153.6110577  108293.45429157 107902.62311952
 107630.54927225 107581.1490589  108151.62637411 106901.47585625
 107007.34313715 106981.16970101 106518.892331   106480.06282347
 106356.17310638 106160.99605777 106463.10203122 106088.22157341
 106044.2436517  105922.06173975 105782.42045755 105650.72087628
 105592.11139293 105692.57340986 105545.69933786 105484.32344363
 105399.72159069 105561.86543468 105338.9449491  105287.18216025
 105308.01424471 105288.76699434 105301.09629252 105083.16374458
 105221.49398961 105103.81844253 104991.63438151 105002.08307334
 104835.41207872 104899.79755473 104810.20056664 104943.14862588
 104897.57366306 104836.19910805 104913.5078211  104827.7779524
 104972.4989314  104693.43598995 104644.30511567 104607.46853244
 104670.89385891 104503.43266135 104444.45801884 104437.2398556
 104530.31619685 104389.0750272  104372.70262359 104485.31721532
 104371.50788891 104487.00023612 104310.06738408 104378.72403635
 104253.67511802 104242.49643074 104233.79938674 104268.46404988
 104203.55482113 104186.17250226 104276.76628174 104193.28927593
 104193.50949192 104222.15965017 104160.70233086 104171.95628289
 104206.18479769 104141.83817112 104056.35087145 104040.42661445
 104020.00505356 104078.37491654 103993.45149173 103986.12466187
 103979.83423053 104000.57595177 104002.48194239 104004.35461406
 103956.71396763 103965.93823783 103947.58584115 103955.7099714
 103873.01572657 103891.71830164 103889.08035196 103890.41547964
 103859.98352342 103886.44446259 103889.02179459 103868.23783583
 103881.2490096  103855.376021   103858.13976457 103841.12741648
 103823.25474688 103836.51451559 103826.45677955 103819.55263955
 103819.65073024 103840.09141501 103793.78340273 103787.91409159
 103805.11633987 103751.63077779 103773.17494157 103746.4640623
 103706.90891771 103710.89552804 103715.09909631 103709.96580161
 103707.10484582 103698.49448017 103721.76884002 103692.11419404
 103701.69554296 103699.95211596 103684.76756905 103692.51880543
 103697.2081802  103677.14725958 103692.77124904 103682.40170949
 103674.61340941 103680.38371757 103679.48043817 103686.14067559
 103678.12247856 103668.48540832 103672.51779567 103676.25426264
 103676.58339208 103682.38181506 103653.06898661 103641.09003415
 103651.83401351 103649.02457738 103634.34171839 103627.94320265
 103627.33158791 103626.30129958 103631.1501698  103627.91621156
 103615.99412093 103612.0116712  103611.56330457 103609.05728235
 103606.54028334 103613.50121562 103603.30034424 103598.56477365
 103599.69545934 103590.33203055 103592.09927265 103596.20537516
 103595.14019451 103590.59346213 103586.18062391 103590.56147888
 103590.85197878 103592.45796504 103578.87190134 103581.28547542
 103585.1443799  103576.32479873 103584.1032443  103571.96063881
 103570.4982196  103572.05183491 103574.41222975 103569.41436651
 103570.26253264 103566.54767237 103559.48968639 103560.34519704
 103560.48363509 103563.51100168 103558.80059293 103557.16188034
 103558.62528902 103554.24219752 103553.64351006 103549.57915836
 103548.58283254 103551.34447413 103549.36018282 103542.5553859
 103543.26174151 103543.528063   103542.67297208 103543.45305262
 103544.9124178  103539.20640732 103541.09904058 103536.24460533
 103538.03343691 103536.59802756 103534.71987126 103534.87967489
 103533.06872993 103535.50622272 103532.07523242 103529.97183084
 103530.76006908 103527.19972394 103527.63123762 103527.42047035
 103526.76855487 103527.02801269 103526.74924082 103527.42767613
 103527.24617278 103526.87298688 103526.03990606 103528.13865571
 103527.03990863 103525.3408963  103525.37041087 103525.5318162
 103525.07897305 103524.67679334 103524.42138376 103524.68215903
 103524.03298364 103524.40971111 103522.16618091 103523.52944648
 103522.54971415 103520.32270296 103519.82130673 103518.97171425
 103518.48350089 103518.9159279  103518.5919044  103518.95891314
 103517.75781979 103518.10459361 103517.63640731 103518.45883682
 103516.92564451 103517.45862472 103515.91152504 103516.73967374
 103515.6973818  103516.49661652 103516.19093958 103515.52176642
 103514.60066348 103513.61198435 103513.92887477 103513.01388499
 103512.94067593 103513.84650273 103512.95435706 103513.60501927
 103511.80187357 103511.29771288 103511.63655918 103510.45518274
 103510.62130999 103511.55699228 103509.61675232 103510.2475371
 103509.37875597 103509.30503212 103509.94440708 103509.14328279
 103508.91650064 103508.43605053 103508.74281083 103507.88408136
 103508.11756238 103507.57974924 103507.18308556 103507.27748236
 103507.17983512 103506.81661165 103506.68402144 103506.65580396
 103506.79942032 103506.45319919 103506.19812244 103506.51997892
 103506.20881937 103506.46773987 103506.11606093 103506.12151982
 103505.93856833 103506.17800655 103505.98638449 103506.11755199
 103505.92921202 103505.86952175 103505.56829449 103505.86562351
 103505.55341805 103505.96651977 103505.51123552 103505.20400949
 103505.17606093 103504.98991337 103505.10345785 103504.9686646
 103504.93885515 103504.99963982 103504.83624539 103504.95046855
 103504.7913145  103504.70264512 103504.58733888 103504.59577849
 103504.48801568 103504.5328403  103504.56878647 103504.49157923
 103504.41049371 103504.36863376 103504.24249032 103504.25873987
 103504.20530728 103504.34945871 103504.21178634 103504.17789082
 103504.17714573 103504.08225712 103504.02450519 103504.03650756
 103504.05330921 103504.04448    103504.10775197 103503.95792969
 103503.93573397 103503.90866014 103503.96492195 103503.92280602
 103503.85305241 103503.94322313 103503.8376892  103503.83962416
 103503.7927272  103503.7747321  103503.76472585 103503.78047971
 103503.77331602 103503.76640132 103503.7872654  103503.77322351
 103503.80299169 103503.82941137 103503.78406763 103503.7491862
 103503.71841556 103503.73498121 103503.7028938  103503.63943233
 103503.63510752 103503.64274078 103503.68878426 103503.66757809
 103503.61764815 103503.62803357 103503.61246413 103503.62512333
 103503.61734535 103503.61085369 103503.62697778 103503.62009865
 103503.60326418 103503.61042505 103503.61732489 103503.62682464
 103503.62428042 103503.62171481 103503.57499626 103503.57758595
 103503.59871772 103503.5820047  103503.56629954 103503.56242871
 103503.55455217 103503.56038485 103503.49991985 103503.48004438
 103503.49885194 103503.48957505 103503.47699588 103503.45456641
 103503.43589217 103503.44052654 103503.4428509  103503.44208749
 103503.43536761 103503.40698989 103503.39969292 103503.38461786
 103503.39506722 103503.39108979 103503.40534797 103503.38244117
 103503.3806199  103503.38374237 103503.39609664 103503.38958469
 103503.39088131 103503.3884908  103503.3941281  103503.38533883
 103503.36341511 103503.36465253 103503.36111979 103503.38254635
 103503.36384665 103503.36721908 103503.37048999 103503.36129442
 103503.3678465  103503.3641394  103503.35462863 103503.3418972
 103503.33469367 103503.34804309]
2025-06-15 09:24:15 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:15 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:15 INFO AOCC mean: 0.0000
2025-06-15 09:24:16 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:17 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:17 ERROR Can not run the algorithm
2025-06-15 09:24:17 INFO Run function 8 complete. FEHistory len: 20, AOCC: 0.0000
2025-06-15 09:24:17 INFO FeHistory: [266766.6817236  197877.75822693 248781.6418238  157597.60039617
 167817.41913212 167793.83392791 229692.65630818 233035.79682345
 175728.46314831 196646.20889575 263159.71842345 198813.07896891
 228065.38338545 223915.62994435 175852.78894891 206744.14717787
 247906.98457297 195373.62125312 183873.50120165 290295.65014591]
2025-06-15 09:24:17 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:17 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:17 INFO AOCC mean: 0.0000
2025-06-15 09:24:22 INFO Run function 8 complete. FEHistory len: 50000, AOCC: 0.0000
2025-06-15 09:24:22 INFO FeHistory: [134673.62560882 176107.16865729 161103.77596261 ...  52558.97856226
  52596.61350744  52630.64677887]
2025-06-15 09:24:22 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:22 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:22 INFO AOCC mean: 0.0000
2025-06-15 09:24:22 INFO Using LLM api key #AIzaSyCbA5uIXRIIWnTv7HCUGX75WoYJ4PeZWd0)
2025-06-15 09:24:22 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:24:22 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:24:29 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:29 INFO Run function 8 complete. FEHistory len: 529, AOCC: 0.0000
2025-06-15 09:24:29 INFO FeHistory: [278718.76837469 269711.64036306 279597.0890819  270413.36055217
 269493.75929416 264371.13783873 260113.51426331 258757.64956945
 265296.418493   258962.51815859 256395.31798909 255311.70468472
 247107.15969106 245216.25750555 251107.56645159 245740.98533903
 247380.5897006  243642.43599948 243028.22242721 238010.8044623
 239605.56532592 243100.1698913  233940.09296234 236820.15031941
 229490.06186157 235203.45002285 234911.08423523 228019.68813848
 224429.80673179 229249.51591199 225928.04575581 225772.54581566
 226462.25771375 226441.86007828 223515.72969347 221145.53644971
 218194.63116107 212147.51221511 220019.38505022 215235.80237193
 207518.47535334 206741.86626411 208144.71737305 209340.21854627
 204745.64571692 206533.57790504 205683.40178836 203574.822216
 204608.36149628 207422.12655922 208063.82634422 203829.29850029
 202363.34810963 202094.8234449  202132.13887959 202410.82721836
 204227.78823892 200763.48444691 203756.19148601 199445.01877634
 201833.63440935 198980.88038328 196987.15085942 198675.24460664
 200165.99304612 196178.74104931 196007.98703675 196992.42386901
 197464.22601739 196195.4326322  194040.85728332 192282.43820855
 193002.31637083 191346.66267161 191482.88489654 190704.45209751
 190521.19411434 190241.30802965 190339.96840848 188950.44134462
 188897.31322831 188367.27891106 188837.13487463 188900.35753975
 186649.70574112 187565.04745794 187884.9678662  187095.58998282
 186621.27572162 186199.44469006 185692.33760194 186277.7499022
 185398.65990725 185412.14483891 184432.05823645 183397.60474407
 183460.10940191 184141.70648775 183559.48789568 182845.21977536
 182977.02459388 183138.19717549 182669.44543085 181979.18282793
 182227.3986022  182088.87074611 182310.89831082 182098.74962362
 181786.57530962 181881.63374253 182746.50385665 181469.45016238
 181493.8973914  182413.44448526 180997.6044744  181009.14153972
 181374.92993164 180922.53881724 181379.42665196 181380.81786408
 180877.45823728 180515.34950732 180850.02468024 180427.95609581
 180357.1508655  180521.20464017 180569.45144061 180315.80390071
 180588.69433196 180371.14672307 180273.62662844 180162.25840579
 179831.11584835 179679.00766326 179966.20849354 179642.96574335
 179309.36560481 179502.62694755 179376.4997894  179552.81905735
 179017.77170434 178697.1049403  178419.72655865 178429.54253879
 178684.505676   178766.7621389  178549.68135767 178138.87644501
 177928.33895432 177752.0756425  177796.57725409 177824.5385039
 177758.06104041 177532.16992406 177306.12806958 177142.51186707
 177168.91619539 177114.35501614 177010.98667423 177092.5747801
 177000.89404763 177062.65230352 177027.49836879 177123.72447021
 176743.91284811 176804.67401708 176824.72480049 176908.74014951
 176800.16395324 176714.60272792 176609.04001514 176637.10572448
 176659.14712891 176620.46369372 176505.46459168 176220.73700646
 176130.10369403 176324.30743169 176394.66353918 176097.49514791
 175914.8975144  175981.9799134  175749.67376071 175696.81903038
 175806.2602373  175832.46227152 175745.00577341 175750.29923863
 175723.7707277  175606.43168223 175611.78517936 175685.92400225
 175639.91078252 175590.75105833 175584.35213535 175626.47620619
 175654.12674539 175480.49858448 175585.07457442 175434.20052368
 175357.29277621 175340.48347855 175213.98838629 175107.8569178
 175127.99629785 175164.64556153 175106.12534338 175201.38975361
 175181.89119302 175167.80811525 175133.30509466 175055.46518594
 175131.51641315 175089.58698672 175044.66507803 175074.82533282
 175105.02197472 175114.51419151 175074.39571342 174997.13085496
 174982.4825502  175016.70022626 175002.09071482 175034.33534793
 174977.91307747 174937.5964236  174877.85847266 174915.8622968
 174845.28268511 174841.99109823 174804.22348433 174830.78457447
 174796.98840674 174808.98818312 174802.86288025 174828.60236135
 174816.9214264  174823.92013511 174739.13734628 174762.42676944
 174737.46207102 174746.11766483 174719.20075189 174707.90916007
 174730.17531674 174695.45484055 174666.56557216 174707.81541779
 174664.13879132 174677.69586302 174666.81217368 174660.96541279
 174646.35315838 174670.10623427 174670.34488564 174639.04382367
 174629.98501598 174615.6160593  174613.01944514 174598.24197138
 174599.68426936 174593.57352156 174569.34360883 174578.86964851
 174583.30446951 174551.68603959 174566.36828279 174540.68297037
 174542.87980427 174560.33019104 174521.02079443 174538.02889307
 174515.82417146 174517.10257199 174521.25190767 174514.32662198
 174513.41716359 174515.21621637 174512.84628523 174517.73302154
 174508.01356288 174500.44516943 174499.7636111  174506.08275513
 174490.72069681 174489.54761408 174494.27097767 174486.03351344
 174487.10608942 174482.86148277 174477.28990325 174471.85593741
 174472.91101956 174465.96970119 174460.01098153 174461.82831652
 174462.37368983 174460.89487422 174459.99253921 174463.01320399
 174456.0807232  174451.31956552 174453.27826857 174441.13008016
 174434.13538689 174434.46127681 174437.58902544 174436.8835096
 174428.95027115 174427.60967081 174419.19942181 174421.31626186
 174414.92734732 174419.29583702 174415.12734542 174416.81224693
 174411.51292203 174410.85659876 174409.45468452 174406.62414299
 174407.24156562 174405.06645296 174406.93136376 174410.13582959
 174403.51401831 174403.31417258 174403.34262    174402.9556501
 174401.04743469 174400.90390831 174401.29189256 174403.23920585
 174399.3617146  174399.86237944 174396.61783528 174396.84184435
 174396.16653962 174395.42577404 174392.37145854 174392.68235634
 174390.99097447 174389.91576353 174388.3128563  174388.0925228
 174388.14105045 174386.19195154 174387.89335102 174387.42997859
 174384.49138408 174383.57820461 174383.92367598 174384.64761839
 174383.45002541 174383.62807622 174384.39078301 174384.66192983
 174384.2982706  174383.26186663 174381.2207068  174380.73659787
 174381.41754665 174380.28944248 174379.84373335 174380.08160761
 174378.47518732 174378.7045078  174378.33026423 174377.20881609
 174376.56846825 174376.8244624  174376.2905245  174376.85064673
 174376.74277921 174376.938673   174376.93072395 174376.80635788
 174376.74241779 174376.73977753 174376.90547914 174376.60015631
 174375.6342242  174375.99860447 174374.97324726 174376.51156546
 174374.9725627  174375.44673134 174374.64111657 174374.1199601
 174374.8095146  174374.63469014 174373.5995927  174374.23518095
 174373.36252199 174373.78906541 174373.07854017 174373.26033238
 174372.74390941 174372.57998648 174372.02855525 174372.41904567
 174371.84560144 174372.41567467 174371.97158344 174371.56783164
 174371.66501874 174371.64909283 174371.52380243 174371.51406858
 174371.44757588 174371.37295714 174371.44271283 174371.24393714
 174371.51308221 174371.13977786 174371.07201778 174371.01572179
 174371.04681561 174370.94982696 174370.88520049 174370.89339591
 174370.81593448 174370.81613582 174370.7041557  174370.67368446
 174370.58980292 174370.48632983 174370.60934839 174370.25400442
 174370.25745326 174370.33179219 174370.30135104 174370.18586791
 174370.33091691 174370.10831072 174370.09020928 174370.19050739
 174370.22117331 174370.10454048 174370.17135669 174369.96457452
 174369.80245595 174369.64821916 174369.65549849 174369.67490828
 174369.52055877 174369.42126098 174369.35290657 174369.35799472
 174369.4342832  174369.21285178 174369.21871728 174369.2634964
 174369.18129972 174369.22641828 174369.20106384 174369.07784913
 174369.12133529 174369.11566556 174369.00650571 174369.07984877
 174369.02579589 174369.06771408 174368.94596109 174369.02402565
 174369.03760836 174368.98206683 174368.98461063 174368.95729539
 174368.84586609 174368.82530134 174368.85463515 174368.87392335
 174368.86721913 174368.80619221 174368.85283716 174368.85706039
 174368.83066375 174368.75086205 174368.81143907 174368.69432335
 174368.7386667  174368.75759289 174368.68048268 174368.69950032
 174368.67538556 174368.68589552 174368.57674652 174368.58398158
 174368.52834144 174368.56203196 174368.53308485 174368.52472731
 174368.493879   174368.5058025  174368.44673815 174368.44551968
 174368.43890353 174368.44633235 174368.43170374 174368.47527155
 174368.40235258 174368.37133481 174368.36036543 174368.37866862
 174368.36586826 174368.34696611 174368.36074323 174368.32834407
 174368.33551996 174368.34361534 174368.33307228 174368.36633506
 174368.32622151 174368.31894761 174368.26361151 174368.26977521
 174368.24633693 174368.25026872 174368.26042218 174368.25008901
 174368.23477097 174368.26369114 174368.23773284 174368.22763653
 174368.21684068 174368.22311778 174368.2295749  174368.18822342
 174368.19458807]
2025-06-15 09:24:29 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:29 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:29 INFO AOCC mean: 0.0000
2025-06-15 09:24:29 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:29 INFO Run function 8 complete. FEHistory len: 585, AOCC: 0.0000
2025-06-15 09:24:29 INFO FeHistory: [262942.16923301 258756.2173834  260771.13394198 258644.69507765
 261493.31917376 261986.81496432 261311.0446256  249250.08399327
 250347.27080001 242584.28483278 236027.63101734 237353.49346973
 236604.24016031 239214.59324373 240589.50358738 242436.63547985
 249266.04566556 233726.33582378 222909.2626058  213114.17440415
 213808.61083657 207354.51644469 211211.03009326 206083.32346072
 204066.39074678 201685.20845525 205693.8691224  205348.26422414
 203111.2951007  201630.89901227 205695.01693019 204284.58411392
 201744.86230015 202275.78037083 199296.49331532 205452.82400813
 203401.39839534 189990.92360808 187919.03375104 184881.45374729
 185121.18687654 184927.27815233 185238.26047175 191556.8582834
 182888.85197429 182043.22876656 179507.39028291 185106.50470368
 179572.2594157  181484.73914587 180382.51261583 177731.32506985
 180050.09940809 176934.28519699 176886.53650575 176292.36036523
 179802.66011212 177729.54267514 176086.66438348 177332.31716519
 178380.60235022 176086.22954697 177433.95715549 177251.67913613
 174920.16993977 175653.86962516 176853.94214821 176770.83032011
 176350.33712714 174419.856496   175530.36316149 173049.47577004
 169694.8873921  172689.80836999 169315.23556206 168707.81237628
 168740.53878838 168534.71937515 170525.69248368 171549.107296
 167717.56845673 166175.08415356 167204.62901604 166403.55572614
 167143.49467678 164693.43311043 164788.32136757 164105.91305184
 165234.50859748 162701.2556436  163393.8838631  160983.26144897
 162234.63029903 158795.06498059 158006.72762229 158025.70458596
 158452.25034507 157829.9105116  157258.54124385 157765.3182929
 157374.24936913 157477.14992942 158510.03405135 159086.75392253
 157875.8834582  156902.31974724 157278.43228312 156476.51062279
 157150.47336266 156069.68532415 155693.38602835 154727.47746909
 156634.01861414 154911.1772153  154095.61679542 154209.08061374
 154703.06767697 153676.07992208 154051.17597493 154406.98479706
 154145.86333988 153430.47341125 153828.43676919 152601.08138938
 152280.48340567 151413.55081349 150999.28385716 150728.76417286
 150193.21012435 150419.90412831 149958.71785046 150158.27944947
 150055.59296781 149989.4267856  149982.91695988 149610.3191045
 149556.98717846 149652.59322315 149613.65525925 149188.87252617
 148983.73851102 149260.21550949 149283.42281211 149558.17411849
 148513.32700264 148501.25404294 148802.79116837 148455.93795337
 147937.32469823 148234.31998972 147845.38956248 148064.75782601
 148023.75516383 147999.77827405 147718.49336425 147474.05519389
 147878.1968951  147857.53513922 147562.54787197 147384.29313797
 147613.13427088 147436.24919009 147586.1794344  147060.03890074
 147053.33310338 146859.96141734 146947.49798614 146987.36162415
 146929.52216506 146812.16531458 146744.1477623  146703.98772838
 146867.56507672 146735.12729918 146659.0576928  146397.64134474
 146404.71020199 146322.04464128 146489.65837051 146259.93410078
 146325.38321489 146073.4606494  146069.98571353 146083.06346443
 146134.29926255 146101.71028677 146129.87255251 146095.20397838
 146107.18303113 146075.34826462 146073.75827359 146191.78297768
 145843.46196446 145999.59047272 145824.68343061 145706.35476673
 145704.88799531 145712.66751727 145637.0864387  145517.82757216
 145507.07822506 145466.93275379 145374.67514496 145417.99321121
 145449.80333192 145389.43931723 145283.15053836 145297.88417547
 145317.27214163 145257.65942898 145260.47145453 145210.70745272
 145233.72421051 145187.02060345 145192.47594631 145155.84676544
 145202.75174943 145112.4874433  145125.46108123 145096.97307319
 145113.36460667 145097.89401974 145102.29500862 145094.58793502
 145055.42183157 145023.35902664 145087.27098443 145035.53783246
 145029.09553987 145107.76660089 145088.69096599 145047.43901548
 145020.52479121 145059.31687067 145012.07127217 144977.90540301
 144980.82730256 144934.56632556 144909.30143401 144915.05519423
 144892.04225373 144860.12492937 144865.461854   144930.35729018
 144870.92799903 144876.87197929 144857.17507857 144857.04647321
 144806.50155891 144832.34807229 144817.35362347 144824.34512232
 144841.38645439 144809.7878605  144764.83454099 144734.31281186
 144719.99714175 144750.00579975 144711.19542249 144730.15584332
 144723.59814896 144722.70964946 144716.79388937 144720.80256994
 144712.15496585 144721.25114781 144682.24754838 144715.564878
 144696.97780128 144700.40043294 144716.25882406 144689.92901966
 144683.17220888 144691.5019667  144695.08239643 144686.68875016
 144698.91930744 144653.80300732 144660.28811126 144674.13614868
 144635.58939823 144635.46461623 144643.0503472  144628.36821943
 144639.44629004 144638.69327352 144634.91861387 144606.0707157
 144585.68395477 144594.68415914 144567.34659553 144561.24983924
 144571.19124484 144576.90932277 144562.4229145  144547.26904282
 144552.96152531 144547.72233068 144543.90386807 144535.59338129
 144545.16104358 144531.78561261 144522.24137965 144531.10367123
 144540.81411391 144530.44887576 144526.96134852 144527.67084017
 144524.49500588 144526.29715082 144527.28419329 144529.15279244
 144525.05353724 144522.43079194 144530.8414022  144512.70911047
 144512.07300552 144524.08146437 144516.54895443 144519.73458857
 144511.51226463 144514.70569304 144517.74259283 144507.70212251
 144508.40478517 144516.59878347 144510.65317777 144513.14300469
 144507.43557283 144520.97079074 144501.95297412 144500.51030284
 144506.70900733 144507.08611839 144495.67581156 144499.24594827
 144497.31195261 144497.7837657  144505.11755108 144487.74652581
 144480.17818739 144480.50125414 144485.47407752 144475.5738998
 144473.61154094 144472.51891707 144474.00653985 144473.97956906
 144473.99073168 144472.50054994 144473.2218014  144473.20317147
 144475.48058526 144478.052179   144473.52642077 144475.937536
 144477.23384488 144472.45588179 144475.96596329 144468.31123047
 144468.63163531 144471.25292737 144468.70189    144468.82112528
 144468.99141902 144469.84923253 144467.2858358  144467.11388802
 144467.37138434 144464.55293783 144464.27937531 144463.66860731
 144464.68214837 144458.99286104 144460.47676396 144459.38122871
 144462.6033259  144461.83031102 144458.14806308 144455.73860651
 144456.05337544 144450.75255702 144447.4393271  144446.86386872
 144443.83590983 144445.1265838  144442.90620155 144444.20696919
 144442.91940122 144441.68472624 144441.98720545 144441.45233924
 144439.57392005 144441.12544924 144441.31063223 144436.90376581
 144438.49546757 144438.29999423 144438.68714735 144436.24754749
 144436.47129298 144436.35616373 144436.7027503  144436.87712095
 144435.33567294 144435.36082874 144433.53123015 144434.05455493
 144436.35535439 144432.93136499 144431.92095505 144432.11169319
 144431.7340846  144432.96199374 144429.73337819 144429.22797304
 144427.55483123 144427.02096383 144425.44257988 144424.61212864
 144425.07054201 144423.962617   144424.60241733 144424.82626294
 144423.43615987 144420.99743568 144421.71827333 144422.1251424
 144421.33561699 144419.91469292 144420.71560184 144419.92069417
 144420.85731332 144420.97828831 144420.17153605 144419.86808953
 144419.71976999 144418.85448836 144419.18434519 144419.08566779
 144419.22366023 144419.09443009 144418.26068252 144418.4578944
 144418.16008135 144418.15646817 144418.6110758  144418.66434279
 144418.14251306 144418.46489761 144418.26214426 144417.83638658
 144417.92173782 144418.0331495  144417.44608682 144417.56147864
 144417.33172985 144417.51121303 144417.82372376 144417.34365906
 144418.24070927 144417.52279275 144416.97617274 144416.49573519
 144415.76726425 144416.07982299 144415.90378123 144416.88307806
 144416.69830738 144415.4411935  144415.43068965 144415.20524091
 144415.71619429 144415.00431279 144415.00230861 144414.74523539
 144414.768096   144415.13099273 144414.42450352 144414.28364193
 144414.1956021  144414.5528439  144414.09156538 144414.06498651
 144413.88742323 144413.92530704 144413.65866718 144413.55110139
 144413.58366945 144413.59759214 144413.64946138 144413.78853123
 144413.7127576  144413.9111285  144413.63283944 144413.52791153
 144413.53804036 144413.76705606 144413.30021036 144413.39430877
 144413.39580092 144413.43738888 144413.19776178 144413.07701622
 144413.22555748 144413.10048467 144412.95714923 144412.91548806
 144412.95193582 144412.88201494 144412.78145517 144412.74592398
 144412.59174417 144412.54136338 144412.44978697 144412.40875621
 144412.33937007 144412.32694315 144412.26398634 144412.19774068
 144412.09514429 144412.04485    144412.01254775 144412.07206708
 144412.02253502 144412.09369415 144411.91880888 144412.04338284
 144411.84567839 144411.93824178 144411.81447869 144411.80067601
 144411.75573812 144411.75302213 144411.80524016 144411.69900901
 144411.67294405 144411.60549874 144411.63758634 144411.60673425
 144411.57178359 144411.59992314 144411.60677977 144411.58591132
 144411.579977   144411.54742522 144411.52831207 144411.52067918
 144411.51963194 144411.5335037  144411.50767255 144411.48284243
 144411.51380703 144411.49966964 144411.46695094 144411.43485253
 144411.42031445 144411.41799049 144411.44349823 144411.42156089
 144411.44964177 144411.37908613 144411.35119379 144411.33737633
 144411.31895291 144411.28952133 144411.29718366 144411.30180698
 144411.28522183 144411.28828416 144411.28842099 144411.27062159
 144411.26508368 144411.29111496 144411.2757666  144411.26077667
 144411.25867653 144411.26323398 144411.26509277 144411.27048786
 144411.27103943 144411.26235618 144411.2848485  144411.25626278
 144411.26154713]
2025-06-15 09:24:29 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:29 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:29 INFO AOCC mean: 0.0000
2025-06-15 09:24:32 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:32 ERROR Can not run the algorithm
2025-06-15 09:24:32 INFO Run function 8 complete. FEHistory len: 303, AOCC: 0.0000
2025-06-15 09:24:32 INFO FeHistory: [204689.16052884 105377.50446638 156570.22633776 168927.49639097
 182086.9042587  124524.69992245 183646.53790064 191662.5676728
 260643.31652299 237044.07527059 241496.4985518  141196.47973573
 191550.41421512 171051.9098321  169480.62028566 167096.01363162
 156766.85033017 183340.39465813 129957.14630454 181284.22353326
 195261.03313566 306837.95901077 203217.90415309 184392.04989178
 294801.3878299  183749.06842133 264154.59224846 183349.59780969
 189247.76908066 117433.00636113 178059.34516385 153748.68857454
 138648.02765945 163766.35672966 229145.02022477 128793.14221058
 192214.25222338 199916.73352032 193756.89444094 226698.29615597
 130995.56397296 258191.72856188 217203.68471056 132752.29605869
 222862.77214099 259340.65960667 100305.79554733 175422.16487979
 278224.29127376 215190.45279227 202417.75718765 105064.9065358
 199484.74130054 237173.34217182 161437.64197022 169493.05710757
 231218.51141314 136043.77622307 138539.53026481 104168.80560896
 206714.78749231 119302.06798602  91533.89721783 143089.02966696
 216592.27347348 233898.73225194 227517.26516329 109738.71594316
 228652.23190713 188607.88849198 184709.15808869 219160.8132866
 183183.76933789 110158.92033203 174863.67221232 247101.10219609
 156955.88127803 227715.08875772 213641.51748562 201180.3044736
 263019.8672959  185105.73071197 209787.32683828 197184.01218501
 313090.08853675 163205.80060462 173865.16076466 224478.21669767
 134365.22706452 212053.00012876 252931.27771739 199447.20848212
 166785.6749583  163188.24564646 157836.82270114 188984.20279458
 149745.49533994 193904.46873181 184151.45794124 209110.07916076
 187200.59143593 133107.4913173  105503.08183142 235234.46751213
 169016.70856615  92435.91244613 226805.24260994 286651.98236557
 226489.41477112 136479.90226443 257490.59595589 177803.04214501
 175198.0351125  114318.88996344 203943.47666656 182688.12674988
 202108.45001906 140622.34718117 214043.898074   185273.59547644
 193092.0240506  195689.6863451  180841.9144807  124387.92385008
 180569.12237827 182259.12806855 118774.64374489 197390.56248648
 147845.61263926 115463.60471227 150530.15578196 145469.36933858
 222875.65281971 237737.12405061 151250.78433323 123783.65487722
 236561.97951422 194649.36530991 129371.3471244  171016.35065264
 162089.98644857 177136.58535165 220846.01064589 115360.04074745
 174192.50637017 152414.14450956 197399.28142755 207603.5062237
 220764.99031323 205568.80133956 188243.11612366 269933.14411967
 176637.42112995 220164.78743815 213194.91040694 216372.55510008
 222989.09900581 160044.10775108 218650.15665953 168949.39746764
 122654.98183328 109736.81276124 230035.84794667 169045.13038045
 215522.27378645 146787.41940829 167267.01573137 166962.19318904
 196990.51704025 207871.41139158 200585.94191516 193821.48484272
 227609.26634359 351908.90020974 223454.47881389 152501.67971159
 269221.98180918 226395.41882165 160619.6487551  218227.82441064
 218009.74159387 182992.82024745 189955.40103721 156835.31693036
 166363.55056938 160504.43177332 213282.40138474 109697.64012876
 165157.73352777 154530.25198897 140484.40297245 205464.02327422
 148776.51603113 233276.65642755 177464.38042652 184139.7279934
 206737.04827857 221273.20847395 187387.6598033  154141.68522286
 155273.71755962 215906.94050082 217330.51136498 222960.03397375
 211329.16472749 122012.42187299 216276.13476923 199809.9638429
 266122.43638198 195670.58885334 144004.40929649 211017.36179737
 154923.7207016  219064.69673875 191454.43727351 194874.24938363
 200886.03206478 180654.70391985 158370.05492726 210735.74680523
 253881.16048138 272005.85238574 119994.85622632 172228.6689157
 143236.30418537 203081.17006075 205412.38876851 232175.1811235
 172356.09624208 195721.76216433 185540.30554278 217641.92742604
 214833.99317478 171477.90837326 239384.72931376 218958.82405544
 228137.48193105 119563.87978975 114984.74873224 225414.07963184
 212649.34429978 255009.27558847 139523.58280846 108705.56439786
 317466.79484837 297114.64723115 114950.76392367 211126.79910184
 163999.79587213 173813.60895485 203965.56726841 170960.91894091
 173342.04974391 198561.88583541 205100.06612842 145276.158322
 243366.04318968 158704.69119409 183929.35059006 191166.71098484
 145671.36107808 208313.48076933 142366.76175484 185590.44768085
 279420.01172287 220007.28206917 214095.1760566  273848.37574428
 244667.36140876 123519.89448771 261645.8440809  203802.62114462
 137889.33501166 141466.28876414 169514.71221076 182644.81001041
 170180.56096505 308309.96438204 222829.98838905 143525.96353307
 226409.03223881 193582.69907511 210702.72621978 196015.71874293
 132451.52776049 184960.0627329  283275.88697903 183562.36399566
 200244.70200623 227147.57939784 264211.64050349 187137.99696067
 198803.85724577 188601.93744352 155434.4917254  187545.43191144
 122581.07738967 264480.04902506 183383.79848726 240777.55440959
 229336.80532212 135295.35704247 118438.74244302]
2025-06-15 09:24:32 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:32 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:32 INFO AOCC mean: 0.0000
2025-06-15 09:24:35 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:24:35 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:24:35 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:24:36 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
.
2025-06-15 09:24:42 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:42 ERROR Can not run the algorithm
2025-06-15 09:24:42 INFO Run function 8 complete. FEHistory len: 10, AOCC: 0.0000
2025-06-15 09:24:42 INFO FeHistory: [226276.74843364 225754.25577103 225811.20659431 226412.97391389
 225603.84785717 227464.03467424 227477.99244545 227637.98234302
 225785.08654707 225825.50525218]
2025-06-15 09:24:42 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:42 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:42 INFO AOCC mean: 0.0000
2025-06-15 09:24:43 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:24:48 INFO Run function 8 complete. FEHistory len: 50000, AOCC: 0.0000
2025-06-15 09:24:48 INFO FeHistory: [149979.64074135 155352.38369684 215854.66330776 ...  39668.57227144
  39668.57227144  39668.57227144]
2025-06-15 09:24:48 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:24:48 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:24:48 INFO AOCC mean: 0.0000
2025-06-15 09:24:54 INFO Using LLM api key #AIzaSyAEUmOe_NUQT_vGqRWH_9XnMDQuUe0CiKU)
2025-06-15 09:24:54 INFO Using LLM api key #AIzaSyCbA5uIXRIIWnTv7HCUGX75WoYJ4PeZWd0)
2025-06-15 09:24:54 INFO Using LLM api key #AIzaSyAEUmOe_NUQT_vGqRWH_9XnMDQuUe0CiKU)
2025-06-15 09:24:55 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
.
2025-06-15 09:24:55 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
.
2025-06-15 09:24:55 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
.
2025-06-15 09:24:55 INFO Using LLM api key #AIzaSyCbA5uIXRIIWnTv7HCUGX75WoYJ4PeZWd0)
2025-06-15 09:24:55 INFO Using LLM api key #AIzaSyAEUmOe_NUQT_vGqRWH_9XnMDQuUe0CiKU)
2025-06-15 09:24:55 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:24:55 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
.
2025-06-15 09:24:55 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
.
2025-06-15 09:24:55 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
.
2025-06-15 09:24:55 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:24:56 INFO Using LLM api key #AIzaSyCbA5uIXRIIWnTv7HCUGX75WoYJ4PeZWd0)
2025-06-15 09:24:56 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:24:56 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
]
.
2025-06-15 09:24:56 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
]
.
2025-06-15 09:24:56 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
]
.
2025-06-15 09:24:56 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:24:56 INFO Using LLM api key #AIzaSyAEUmOe_NUQT_vGqRWH_9XnMDQuUe0CiKU)
2025-06-15 09:24:56 INFO Using LLM api key #AIzaSyCbA5uIXRIIWnTv7HCUGX75WoYJ4PeZWd0)
2025-06-15 09:24:57 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
]
.
2025-06-15 09:24:57 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
]
.
2025-06-15 09:25:04 INFO --- GNBG Problem Parameters for f8 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -656.788998
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0.2 0.2]
----------------------------------------
2025-06-15 09:25:04 ERROR Can not run the algorithm
2025-06-15 09:25:04 INFO Run function 8 complete. FEHistory len: 20, AOCC: 0.0000
2025-06-15 09:25:04 INFO FeHistory: [138950.64535577 137707.85275132 136480.87085025 137715.23774243
 137351.09280289 136694.61974994 138235.30331128 138546.96554467
 138550.73438728 137542.32809162 138649.59083321 140027.99747455
 139232.55738104 139579.95272032 138200.80294944 137773.4762939
 140200.71636214 137312.54165421 138791.39560863 138474.93277199]
2025-06-15 09:25:04 INFO Expected Optimum FE: -656.7889979935655
2025-06-15 09:25:04 INFO Multimodal (single component) AOCC mean: 0.0000
2025-06-15 09:25:04 INFO AOCC mean: 0.0000
2025-06-15 09:25:04 INFO Using LLM api key #AIzaSyAEUmOe_NUQT_vGqRWH_9XnMDQuUe0CiKU)
2025-06-15 09:25:04 INFO Using LLM api key #AIzaSyCbA5uIXRIIWnTv7HCUGX75WoYJ4PeZWd0)
2025-06-15 09:25:04 INFO Using LLM api key #AIzaSyAEUmOe_NUQT_vGqRWH_9XnMDQuUe0CiKU)
2025-06-15 09:25:04 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
.
2025-06-15 09:25:04 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
.
2025-06-15 09:25:04 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
.
2025-06-15 09:25:04 INFO Using LLM api key #AIzaSyCbA5uIXRIIWnTv7HCUGX75WoYJ4PeZWd0)
2025-06-15 09:25:04 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:25:04 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:25:05 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
.
2025-06-15 09:25:05 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
.
2025-06-15 09:25:05 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
.
2025-06-15 09:25:05 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:25:05 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:25:05 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:25:05 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
.
2025-06-15 09:25:05 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
.
2025-06-15 09:25:05 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
.
2025-06-15 09:25:05 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:25:05 INFO Using LLM api key #AIzaSyAS4WrMPg7WNPXLpCYIOG49cIYOL7vTAl8)
2025-06-15 09:25:05 INFO Using LLM api key #AIzaSyARJfdVOsI9AKUK6gxvUszL_bn5Z_lr5Wg)
2025-06-15 09:25:06 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
]
.
2025-06-15 09:25:06 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
]
.
2025-06-15 09:25:06 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea_api_rotations.py", line 329, in evolve_solution
    evolved_individual = chosen_llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 278, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
]
.
